---
exclude: ['Makefile', 'README.md', 'Gemfile', 'Gemfile.lock']
permalink: /:categories/:year/:title/ 
highlighter: pygments
safe: false
title: Trevor O
production_url: http://trevoro.net
author:
  name: Trevor O
  gravatar: 24969c869ebd849cbe81575761daad15 
  email: trevoro@gmail.com
  twitter: trevoro
  github: trevoro
assets:
  compress:
    js: uglifier
    css: sass
plugins:
  - jekyll-feed
  - jekyll-sitemap
